### ISSUE TITLE
"Asynchronous programming patterns with Mojo::IOLoop::Delay"

### ISSUE THREAD

**Issue by mpapec** [scottw/p5-Business-PayPal-NVP#2]
Hello Scott,

I was watching your presentation on Delay pattern,
https://www.youtube.com/watch?v=YYVFaHkASZY

and I'm curious how to properly handle optional steps which execution depend on previous async results. I've ended up with,

unshift @{$d->remaining}, sub {..};

but feel uncomfortable with such logic flow.

https://gist.github.com/mpapec/8713a3cf2c1da8187e7d00704a411bd1
(if (1).. is for demonstration only)

Can you suggest some pointers how to approach this problem?

regards

ps. I'm sorry for spamming your paypal project

**Comment by scottw** [comment]
my email is scott@perlcode.org (I replied on your gist, btw.)
